- hosts: localhost

  tasks:
  - name: Install Packer for Neovim
    git:
      repo: https://github.com/wbthomason/packer.nvim
      dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      update: no
