---
- hosts: localhost
  connection: local

  tasks:
  - name: Install Flathub repo 
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    become: yes

  - name: Install Flatpaks
    community.general.flatpak:
      name:
        - chat.delta.desktop
        - com.github.tchx84.Flatseal
        - com.spotify.Client
        - org.signal.Signal
        - com.belmoussaoui.Obfuscate
