---
- hosts: localhost
  connection: local

  tasks:
  - name: Install Flatpaks
    community.general.flatpak:
      name:
        - chat.delta.desktop
        - com.github.tchx84.Flatseal
        - com.spotify.Client
        - org.signal.Signal
        - com.belmoussaoui.Obfuscate
