---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Disable Software Search after Command Not Found
    lineinfile:
      path: /etc/PackageKit/CommandNotFound.conf
      regexp: "^SoftwareSourceSearch="
      line: "SoftwareSourceSearch=false"
