- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/ibm.yaml | uinput -d $DEVNODE"
  DEVICE:
    NAME: "Lite-On Tech IBM USB Travel Keyboard with Ultra Nav"
- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/lenovo.yaml | uinput -d $DEVNODE"
  DEVICE:
    NAME: "AT Translated Set 2 keyboard"
