- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/ibm.yaml | uinput -d $DEVNODE"
  DEVICE:
    NAME: "Lite-On Tech IBM USB Travel Keyboard with Ultra Nav"
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_LEFTSHIFT, KEY_RIGHTSHIFT, KEY_LEFTCTRL]
- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/lenovo.yaml | uinput -d $DEVNODE"
  DEVICE:
    NAME: "AT Translated Set 2 keyboard"
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_LEFTSHIFT, KEY_RIGHTSHIFT]

