dnf_packages:
  - fzf
  - git
  - gpg
  - grc
  - java-latest-openjdk
  - maim
  - neofetch
  - neovim
  - nmap
  - npm
  - p7zip
  - pipenv
  - pulseaudio-utils
  - python
  - ripgrep
  - stow
  - sqlite
  - tealdeer
  - trash-cli
  - toilet
  - unzip
  - util-linux-user
  - youtube-dl
  - zsh
dnf_gui_packages:
  - audacity
  - evolution
  - fira-code-fonts
  - firewall-config
  - foliate
  - gimp
  - gnome-epub-thumbnailer
  - gnome-tweaks
  - gparted
  - kitty
  - pavucontrol
  - peek
  - obs-studio
  - vlc
  - wl-clipboard
