---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
  - name: Update DNF Cache
    dnf: update_cache=yes

  tasks:
  - name: Disable Software Search after Command Not Found
    lineinfile:
      path: /etc/PackageKit/CommandNotFound.conf
      regexp: "^SoftwareSourceSearch="
      line: "SoftwareSourceSearch=false"

  - name: Enable RPM Fusion
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm,https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      state: present

  - name: Install Multimedia
    dnf: name="@Multimedia"

  - name: Install Development Tools
    dnf: name="@Development Tools"

  - name: Install DNF packages
    dnf: name="{{ dnf_packages }}"

  - name: Install GUI related packages
    dnf: name="{{ dnf_gui_packages }}"
